import 'package:flutter/material.dart'
    show
        BuildContext,
        Card,
        Center,
        EdgeInsets,
        GridView,
        Icon,
        IconData,
        Icons,
        SliverGridDelegateWithFixedCrossAxisCount,
        StatelessWidget,
        Widget;

class IconsScreen extends StatelessWidget {
  const IconsScreen({super.key});

  static final List<IconData> _icons = [
    Icons.home,
    Icons.star,
    Icons.favorite,
    Icons.settings,
    Icons.search,
    Icons.person,
    Icons.add,
    Icons.edit,
    Icons.delete,
    Icons.save,
    Icons.share,
    Icons.check,
    Icons.close,
    Icons.menu,
    Icons.arrow_back,
    Icons.arrow_forward,
    Icons.arrow_upward,
    Icons.arrow_downward,
    Icons.refresh,
    Icons.info,
    Icons.warning,
    Icons.error,
    Icons.help,
    Icons.notifications,
    Icons.email,
    Icons.phone,
    Icons.message,
    Icons.camera,
    Icons.photo,
    Icons.video_camera_back,
    Icons.music_note,
    Icons.volume_up,
    Icons.volume_down,
    Icons.volume_off,
    Icons.play_arrow,
    Icons.pause,
    Icons.stop,
    Icons.skip_next,
    Icons.skip_previous,
    Icons.fast_forward,
    Icons.fast_rewind,
    Icons.calendar_today,
    Icons.access_time,
    Icons.lock,
    Icons.lock_open,
    Icons.visibility,
    Icons.visibility_off,
    Icons.cloud,
    Icons.cloud_upload,
    Icons.cloud_download,
    Icons.attachment,
    Icons.folder,
    Icons.folder_open,
    Icons.insert_drive_file,
    Icons.description,
    Icons.picture_as_pdf,
    Icons.image,
    Icons.location_on,
    Icons.map,
    Icons.navigation,
    Icons.explore,
    Icons.directions,
    Icons.local_cafe,
    Icons.local_dining,
    Icons.local_hospital,
    Icons.local_hotel,
    Icons.local_pharmacy,
    Icons.shopping_cart,
    Icons.shopping_bag,
    Icons.store,
    Icons.card_giftcard,
    Icons.credit_card,
    Icons.account_balance,
    Icons.monetization_on,
    Icons.trending_up,
    Icons.trending_down,
    Icons.bar_chart,
    Icons.pie_chart,
    Icons.show_chart,
    Icons.timeline,
    Icons.language,
    Icons.translate,
    Icons.public,
    Icons.vpn_lock,
    Icons.wifi,
    Icons.bluetooth,
    Icons.battery_full,
    Icons.brightness_high,
    Icons.brightness_low,
    Icons.flashlight_on,
    Icons.flashlight_off,
    Icons.airplanemode_active,
    Icons.print,
    Icons.computer,
    Icons.keyboard,
    Icons.mouse,
    Icons.headset,
    Icons.watch,
  ];

  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      padding: const EdgeInsets.all(8.0),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 5,
        crossAxisSpacing: 8.0,
        mainAxisSpacing: 8.0,
      ),
      itemCount: _icons.length,
      itemBuilder: (context, index) {
        return Card(child: Center(child: Icon(_icons[index], size: 32.0)));
      },
    );
  }
}
