# FastAPI router for Note endpoints
# Generated from OpenAPI specification

from typing import List
import uuid
from fastapi import APIRouter, HTTPException, status, Depends
from sqlalchemy.orm import Session
from app.auth import get_current_user
from app.autogenerated.pydantic_models import (
    Note as NoteResponse,
    CreateNoteRequest,
    UpdateNoteRequest,
    ErrorResponse,
)
from app.models.note import Note as NoteModel
from app.models.user import User as UserModel
from app.database import get_db

router = APIRouter(prefix="/api/note", tags=["Note"])


@router.get(
    "",
    response_model=List[NoteResponse],
    status_code=status.HTTP_200_OK,
    responses={
        500: {"model": ErrorResponse, "description": "Server error"},
    },
    summary="List all notes for the authenticated user",
)
async def list_notes(
    current_user: UserModel = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> List[NoteResponse]:
    """List all notes for the authenticated user."""
    notes = db.query(NoteModel).filter(NoteModel.user_id == current_user.id).all()

    return [
        NoteResponse(
            id=note.id,
            title=note.title,
            content=note.content,
            user_id=note.user_id,
            date_created=note.date_created,
            date_updated=note.date_updated,
        )
        for note in notes
    ]


@router.post(
    "",
    response_model=NoteResponse,
    status_code=status.HTTP_201_CREATED,
    responses={
        400: {"model": ErrorResponse, "description": "Bad request"},
        500: {"model": ErrorResponse, "description": "Server error"},
    },
    summary="Create a new note",
)
async def create_note(
    note_data: CreateNoteRequest,
    current_user: UserModel = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> NoteResponse:
    """Create a new note."""
    note = NoteModel(
        id=str(uuid.uuid4()),
        title=note_data.title,
        content=note_data.content,
        user_id=current_user.id,
    )

    db.add(note)
    db.commit()
    db.refresh(note)

    return NoteResponse(
        id=note.id,
        title=note.title,
        content=note.content,
        user_id=note.user_id,
        date_created=note.date_created,
        date_updated=note.date_updated,
    )


@router.get(
    "/{id}",
    response_model=NoteResponse,
    status_code=status.HTTP_200_OK,
    responses={
        404: {"model": ErrorResponse, "description": "Note not found"},
        500: {"model": ErrorResponse, "description": "Server error"},
    },
    summary="Get a specific note by ID",
)
async def get_note(
    id: str,
    current_user: UserModel = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> NoteResponse:
    """Get a specific note by ID."""
    note = db.query(NoteModel).filter(
        NoteModel.id == id,
        NoteModel.user_id == current_user.id
    ).first()

    if not note:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Note not found"
        )

    return NoteResponse(
        id=note.id,
        title=note.title,
        content=note.content,
        user_id=note.user_id,
        date_created=note.date_created,
        date_updated=note.date_updated,
    )


@router.patch(
    "/{id}",
    response_model=NoteResponse,
    status_code=status.HTTP_200_OK,
    responses={
        400: {"model": ErrorResponse, "description": "Bad request"},
        404: {"model": ErrorResponse, "description": "Note not found"},
        500: {"model": ErrorResponse, "description": "Server error"},
    },
    summary="Update a note",
)
async def update_note(
    id: str,
    note_data: UpdateNoteRequest,
    current_user: UserModel = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> NoteResponse:
    """Update a note."""
    note = db.query(NoteModel).filter(
        NoteModel.id == id,
        NoteModel.user_id == current_user.id
    ).first()

    if not note:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Note not found"
        )

    if note_data.title is not None:
        note.title = note_data.title
    if note_data.content is not None:
        note.content = note_data.content

    db.commit()
    db.refresh(note)

    return NoteResponse(
        id=note.id,
        title=note.title,
        content=note.content,
        user_id=note.user_id,
        date_created=note.date_created,
        date_updated=note.date_updated,
    )


@router.delete(
    "/{id}",
    status_code=status.HTTP_204_NO_CONTENT,
    responses={
        404: {"model": ErrorResponse, "description": "Note not found"},
        500: {"model": ErrorResponse, "description": "Server error"},
    },
    summary="Delete a note",
)
async def delete_note(
    id: str,
    current_user: UserModel = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Delete a note."""
    note = db.query(NoteModel).filter(
        NoteModel.id == id,
        NoteModel.user_id == current_user.id
    ).first()

    if not note:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Note not found"
        )

    db.delete(note)
    db.commit()
