// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZztg4l_y_G2t64akrR-9kSWW5VV66gDI',
    appId: '1:762525351037:web:e70494ed54c992a8310514',
    messagingSenderId: '762525351037',
    projectId: 'simple-flutter-template',
    authDomain: 'simple-flutter-template.firebaseapp.com',
    storageBucket: 'simple-flutter-template.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA0DAlN_cW36UzE_uDVdVrpvFlUOPIlz8',
    appId: '1:762525351037:android:303ded1597c4a7be310514',
    messagingSenderId: '762525351037',
    projectId: 'simple-flutter-template',
    storageBucket: 'simple-flutter-template.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoZFgjuRqjGwpbrK25jtigr3EOx6og3Vg',
    appId: '1:762525351037:ios:62a5a5d7ddf363d5310514',
    messagingSenderId: '762525351037',
    projectId: 'simple-flutter-template',
    storageBucket: 'simple-flutter-template.firebasestorage.app',
    androidClientId:
        '762525351037-7mfrdt0ik62t17ut2q50os0oqkueljf8.apps.googleusercontent.com',
    iosClientId:
        '762525351037-7bfus7qi2rcsp06piaqhff203f64mfi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoZFgjuRqjGwpbrK25jtigr3EOx6og3Vg',
    appId: '1:762525351037:ios:62a5a5d7ddf363d5310514',
    messagingSenderId: '762525351037',
    projectId: 'simple-flutter-template',
    storageBucket: 'simple-flutter-template.firebasestorage.app',
    androidClientId:
        '762525351037-7mfrdt0ik62t17ut2q50os0oqkueljf8.apps.googleusercontent.com',
    iosClientId:
        '762525351037-7bfus7qi2rcsp06piaqhff203f64mfi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZztg4l_y_G2t64akrR-9kSWW5VV66gDI',
    appId: '1:762525351037:web:276dcf9b25fa9aca310514',
    messagingSenderId: '762525351037',
    projectId: 'simple-flutter-template',
    authDomain: 'simple-flutter-template.firebaseapp.com',
    storageBucket: 'simple-flutter-template.firebasestorage.app',
  );
}
