"""Add recurring todo fields and constraints

Revision ID: 12052354c204
Revises: 846bb0e38268
Create Date: 2025-12-10 00:10:40.016007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12052354c204'
down_revision: Union[str, Sequence[str], None] = '846bb0e38268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create FrequencyKind enum type
    frequency_kind_enum = postgresql.ENUM('specific-days-per-week', 'multiple-days-per-week', 'specific-day-of-month', 'multiple-days-per-month', name='FrequencyKind')
    frequency_kind_enum.create(op.get_bind())

    op.add_column('todos', sa.Column('frequency_kind', sa.Enum('specific-days-per-week', 'multiple-days-per-week', 'specific-day-of-month', 'multiple-days-per-month', name='FrequencyKind'), nullable=True))
    op.add_column('todos', sa.Column('days_of_week', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('todos', sa.Column('num_times_per_week', sa.Integer(), nullable=True))
    op.add_column('todos', sa.Column('num_times_per_month', sa.Integer(), nullable=True))
    op.add_column('todos', sa.Column('day_of_month', sa.Integer(), nullable=True))

    # Add check constraints
    # Note: days_of_week integer array validation is done at application level
    # (PostgreSQL doesn't allow subqueries in CHECK constraints)
    op.create_check_constraint(
        'ck_specific_days_per_week_requires_days',
        'todos',
        "frequency_kind != 'specific-days-per-week' OR days_of_week IS NOT NULL"
    )
    op.create_check_constraint(
        'ck_multiple_days_per_week_requires_num_times',
        'todos',
        "frequency_kind != 'multiple-days-per-week' OR num_times_per_week IS NOT NULL"
    )
    op.create_check_constraint(
        'ck_specific_day_of_month_requires_day',
        'todos',
        "frequency_kind != 'specific-day-of-month' OR day_of_month IS NOT NULL"
    )
    op.create_check_constraint(
        'ck_multiple_days_per_month_requires_num_times',
        'todos',
        "frequency_kind != 'multiple-days-per-month' OR num_times_per_month IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop check constraints
    op.drop_constraint('ck_multiple_days_per_month_requires_num_times', 'todos', type_='check')
    op.drop_constraint('ck_specific_day_of_month_requires_day', 'todos', type_='check')
    op.drop_constraint('ck_multiple_days_per_week_requires_num_times', 'todos', type_='check')
    op.drop_constraint('ck_specific_days_per_week_requires_days', 'todos', type_='check')

    op.drop_column('todos', 'day_of_month')
    op.drop_column('todos', 'num_times_per_month')
    op.drop_column('todos', 'num_times_per_week')
    op.drop_column('todos', 'days_of_week')
    op.drop_column('todos', 'frequency_kind')

    # Drop FrequencyKind enum type
    frequency_kind_enum = postgresql.ENUM('specific-days-per-week', 'multiple-days-per-week', 'specific-day-of-month', 'multiple-days-per-month', name='FrequencyKind')
    frequency_kind_enum.drop(op.get_bind())
    # ### end Alembic commands ###
