"""Add timer_log field to todos

Revision ID: 2dcfee301db7
Revises: 658fd905e761
Create Date: 2025-11-27 12:45:47.104481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dcfee301db7'
down_revision: Union[str, Sequence[str], None] = '658fd905e761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('timer_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'timer_log')
    # ### end Alembic commands ###
