"""initial schema

Revision ID: 3a751bbbbab8
Revises: 
Create Date: 2026-01-11 22:20:18.706868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a751bbbbab8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('funs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('order', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'COMPLETE', 'ARCHIVED', 'WAITING', name='TodoStatus'), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('order', sa.String(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('time_estimate', sa.Enum('1-min', '5-mins', '15-mins', '30-mins', '1-hour', '2-hours', 'half-day', 'one-day', 'project', name='TimeEstimate'), nullable=True),
    sa.Column('annoyingness', sa.Integer(), server_default='0', nullable=False),
    sa.Column('committed', sa.Boolean(), nullable=False),
    sa.Column('timer_log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('atomic', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('infinitely_divisible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('kind', sa.Enum('REGULAR', 'BREAK_UP', 'HABIT', name='TodoKind'), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('frequency_kind', sa.Enum('specific-days-per-week', 'multiple-days-per-week', 'specific-day-of-month', 'multiple-days-per-month', name='FrequencyKind'), nullable=True),
    sa.Column('days_of_week', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('num_times_per_week', sa.Integer(), nullable=True),
    sa.Column('num_times_per_month', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.CheckConstraint("frequency_kind != 'multiple-days-per-month' OR num_times_per_month IS NOT NULL", name='ck_multiple_days_per_month_requires_num_times'),
    sa.CheckConstraint("frequency_kind != 'multiple-days-per-week' OR num_times_per_week IS NOT NULL", name='ck_multiple_days_per_week_requires_num_times'),
    sa.CheckConstraint("frequency_kind != 'specific-day-of-month' OR day_of_month IS NOT NULL", name='ck_specific_day_of_month_requires_day'),
    sa.CheckConstraint("frequency_kind != 'specific-days-per-week' OR days_of_week IS NOT NULL", name='ck_specific_days_per_week_requires_days'),
    sa.ForeignKeyConstraint(['parent_id'], ['todos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_user_habit_order', 'todos', ['user_id', 'order'], unique=True, postgresql_where=sa.text("kind = 'HABIT'"))
    op.create_index('uq_user_order', 'todos', ['user_id', 'order'], unique=True, postgresql_where=sa.text("kind IN ('REGULAR', 'BREAK_UP')"))
    op.create_table('habit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('habit_id', sa.String(), nullable=False),
    sa.Column('when', sa.Date(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['todos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_logs')
    op.drop_index('uq_user_order', table_name='todos', postgresql_where=sa.text("kind IN ('REGULAR', 'BREAK_UP')"))
    op.drop_index('uq_user_habit_order', table_name='todos', postgresql_where=sa.text("kind = 'HABIT'"))
    op.drop_table('todos')
    op.drop_table('funs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
