"""Add kind field and TodoKind enum to todo model

Revision ID: 3e219e129cc5
Revises: b460478a09be
Create Date: 2025-12-02 20:57:08.101033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e219e129cc5'
down_revision: Union[str, Sequence[str], None] = 'b460478a09be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    todokind_enum = sa.Enum('REGULAR', 'BREAK_UP', name='todokind')
    todokind_enum.create(op.get_bind(), checkfirst=True)

    # Add column with default value for existing rows
    op.add_column('todos', sa.Column('kind', todokind_enum, nullable=False, server_default='REGULAR'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'kind')
    # Drop the enum type
    sa.Enum(name='todokind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
