"""make_user_order_constraint_conditional_on_kind

Revision ID: 49832d434b59
Revises: 12052354c204
Create Date: 2025-12-11 09:11:32.369944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49832d434b59'
down_revision: Union[str, Sequence[str], None] = '12052354c204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_order'), 'todos', type_='unique')
    op.create_index('uq_user_order', 'todos', ['user_id', 'order'], unique=True, postgresql_where=sa.text("kind IN ('REGULAR'::todokind, 'BREAK_UP'::todokind)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_order', table_name='todos', postgresql_where=sa.text("kind IN ('REGULAR'::todokind, 'BREAK_UP'::todokind)"))
    op.create_unique_constraint(op.f('uq_user_order'), 'todos', ['user_id', 'order'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
