"""Add parent_id to todos table

Revision ID: 6489c3340586
Revises: 3e219e129cc5
Create Date: 2025-12-02 20:59:49.311670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6489c3340586'
down_revision: Union[str, Sequence[str], None] = '3e219e129cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('parent_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todos', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'parent_id')
    # ### end Alembic commands ###
