"""Add atomic and infinitely_divisible fields to todos

Revision ID: b460478a09be
Revises: 2dcfee301db7
Create Date: 2025-12-02 20:18:36.873035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b460478a09be'
down_revision: Union[str, Sequence[str], None] = '2dcfee301db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('atomic', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('todos', sa.Column('infinitely_divisible', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'infinitely_divisible')
    op.drop_column('todos', 'atomic')
    # ### end Alembic commands ###
