// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthApiGetCurrentUserData, AuthApiGetCurrentUserErrors, AuthApiGetCurrentUserResponses, AuthApiLoginData, AuthApiLoginErrors, AuthApiLoginResponses, AuthApiLogoutData, AuthApiLogoutErrors, AuthApiLogoutResponses, AuthApiRefreshTokenData, AuthApiRefreshTokenErrors, AuthApiRefreshTokenResponses, AuthApiRegisterData, AuthApiRegisterErrors, AuthApiRegisterResponses, NoteApiCreateData, NoteApiCreateErrors, NoteApiCreateResponses, NoteApiDeleteData, NoteApiDeleteErrors, NoteApiDeleteResponses, NoteApiGetData, NoteApiGetErrors, NoteApiGetResponses, NoteApiListData, NoteApiListErrors, NoteApiListResponses, NoteApiUpdateData, NoteApiUpdateErrors, NoteApiUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login with email and password
 */
export const authApiLogin = <ThrowOnError extends boolean = false>(options: Options<AuthApiLoginData, ThrowOnError>) => (options.client ?? client).post<AuthApiLoginResponses, AuthApiLoginErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout user by clearing refresh token cookie
 */
export const authApiLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthApiLogoutData, ThrowOnError>) => (options?.client ?? client).post<AuthApiLogoutResponses, AuthApiLogoutErrors, ThrowOnError>({ url: '/api/auth/logout', ...options });

/**
 * Get current authenticated user
 */
export const authApiGetCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<AuthApiGetCurrentUserData, ThrowOnError>) => (options?.client ?? client).get<AuthApiGetCurrentUserResponses, AuthApiGetCurrentUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});

/**
 * Refresh access token using refresh token from httpOnly cookie
 */
export const authApiRefreshToken = <ThrowOnError extends boolean = false>(options?: Options<AuthApiRefreshTokenData, ThrowOnError>) => (options?.client ?? client).post<AuthApiRefreshTokenResponses, AuthApiRefreshTokenErrors, ThrowOnError>({ url: '/api/auth/refresh', ...options });

/**
 * Register a new user
 */
export const authApiRegister = <ThrowOnError extends boolean = false>(options: Options<AuthApiRegisterData, ThrowOnError>) => (options.client ?? client).post<AuthApiRegisterResponses, AuthApiRegisterErrors, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all notes for the authenticated user
 */
export const noteApiList = <ThrowOnError extends boolean = false>(options?: Options<NoteApiListData, ThrowOnError>) => (options?.client ?? client).get<NoteApiListResponses, NoteApiListErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/note',
    ...options
});

/**
 * Create a new note
 */
export const noteApiCreate = <ThrowOnError extends boolean = false>(options: Options<NoteApiCreateData, ThrowOnError>) => (options.client ?? client).post<NoteApiCreateResponses, NoteApiCreateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/note',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a note
 */
export const noteApiDelete = <ThrowOnError extends boolean = false>(options: Options<NoteApiDeleteData, ThrowOnError>) => (options.client ?? client).delete<NoteApiDeleteResponses, NoteApiDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/note/{id}',
    ...options
});

/**
 * Get a specific note by ID
 */
export const noteApiGet = <ThrowOnError extends boolean = false>(options: Options<NoteApiGetData, ThrowOnError>) => (options.client ?? client).get<NoteApiGetResponses, NoteApiGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/note/{id}',
    ...options
});

/**
 * Update a note
 */
export const noteApiUpdate = <ThrowOnError extends boolean = false>(options: Options<NoteApiUpdateData, ThrowOnError>) => (options.client ?? client).patch<NoteApiUpdateResponses, NoteApiUpdateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/note/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
