// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type CreateNoteRequest = {
    title: string;
    content: string;
};

export type ErrorResponse = {
    message: string;
    code?: string;
};

export type Note = {
    id: string;
    title: string;
    content: string;
    user_id: string;
    date_created: string;
    date_updated: string;
};

export type Token = {
    access_token: string;
    token_type: string;
};

export type UpdateNoteRequest = {
    title?: string;
    content?: string;
};

export type User = {
    id: string;
    email: string;
    is_active: boolean;
    date_created: string;
    date_updated: string;
};

export type UserLoginRequest = {
    email: string;
    password: string;
};

export type UserRegisterRequest = {
    email: string;
    password: string;
};

export type AuthApiLoginData = {
    body: UserLoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthApiLoginErrors = {
    /**
     * Access is unauthorized.
     */
    401: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type AuthApiLoginError = AuthApiLoginErrors[keyof AuthApiLoginErrors];

export type AuthApiLoginResponses = {
    /**
     * The request has succeeded.
     */
    200: Token;
};

export type AuthApiLoginResponse = AuthApiLoginResponses[keyof AuthApiLoginResponses];

export type AuthApiLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthApiLogoutErrors = {
    /**
     * Access is unauthorized.
     */
    401: ErrorResponse;
};

export type AuthApiLogoutError = AuthApiLogoutErrors[keyof AuthApiLogoutErrors];

export type AuthApiLogoutResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type AuthApiGetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type AuthApiGetCurrentUserErrors = {
    /**
     * Access is unauthorized.
     */
    401: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type AuthApiGetCurrentUserError = AuthApiGetCurrentUserErrors[keyof AuthApiGetCurrentUserErrors];

export type AuthApiGetCurrentUserResponses = {
    /**
     * The request has succeeded.
     */
    200: User;
};

export type AuthApiGetCurrentUserResponse = AuthApiGetCurrentUserResponses[keyof AuthApiGetCurrentUserResponses];

export type AuthApiRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type AuthApiRefreshTokenErrors = {
    /**
     * Access is unauthorized.
     */
    401: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type AuthApiRefreshTokenError = AuthApiRefreshTokenErrors[keyof AuthApiRefreshTokenErrors];

export type AuthApiRefreshTokenResponses = {
    /**
     * The request has succeeded.
     */
    200: Token;
};

export type AuthApiRefreshTokenResponse = AuthApiRefreshTokenResponses[keyof AuthApiRefreshTokenResponses];

export type AuthApiRegisterData = {
    body: UserRegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type AuthApiRegisterErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type AuthApiRegisterError = AuthApiRegisterErrors[keyof AuthApiRegisterErrors];

export type AuthApiRegisterResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: User;
};

export type AuthApiRegisterResponse = AuthApiRegisterResponses[keyof AuthApiRegisterResponses];

export type NoteApiListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/note';
};

export type NoteApiListErrors = {
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type NoteApiListError = NoteApiListErrors[keyof NoteApiListErrors];

export type NoteApiListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<Note>;
};

export type NoteApiListResponse = NoteApiListResponses[keyof NoteApiListResponses];

export type NoteApiCreateData = {
    body: CreateNoteRequest;
    path?: never;
    query?: never;
    url: '/api/note';
};

export type NoteApiCreateErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type NoteApiCreateError = NoteApiCreateErrors[keyof NoteApiCreateErrors];

export type NoteApiCreateResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: Note;
};

export type NoteApiCreateResponse = NoteApiCreateResponses[keyof NoteApiCreateResponses];

export type NoteApiDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/note/{id}';
};

export type NoteApiDeleteErrors = {
    /**
     * The server cannot find the requested resource.
     */
    404: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type NoteApiDeleteError = NoteApiDeleteErrors[keyof NoteApiDeleteErrors];

export type NoteApiDeleteResponses = {
    /**
     * There is no content to send for this request, but the headers may be useful.
     */
    204: void;
};

export type NoteApiDeleteResponse = NoteApiDeleteResponses[keyof NoteApiDeleteResponses];

export type NoteApiGetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/note/{id}';
};

export type NoteApiGetErrors = {
    /**
     * The server cannot find the requested resource.
     */
    404: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type NoteApiGetError = NoteApiGetErrors[keyof NoteApiGetErrors];

export type NoteApiGetResponses = {
    /**
     * The request has succeeded.
     */
    200: Note;
};

export type NoteApiGetResponse = NoteApiGetResponses[keyof NoteApiGetResponses];

export type NoteApiUpdateData = {
    body: UpdateNoteRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/note/{id}';
};

export type NoteApiUpdateErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ErrorResponse;
    /**
     * The server cannot find the requested resource.
     */
    404: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type NoteApiUpdateError = NoteApiUpdateErrors[keyof NoteApiUpdateErrors];

export type NoteApiUpdateResponses = {
    /**
     * The request has succeeded.
     */
    200: Note;
};

export type NoteApiUpdateResponse = NoteApiUpdateResponses[keyof NoteApiUpdateResponses];
