import { client } from './api-client/client.gen';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

// Token management utilities
export const authTokenManager = {
    getToken(): string | null {
        return localStorage.getItem('auth_token');
    },

    setToken(token: string): void {
        localStorage.setItem('auth_token', token);
    },

    clearToken(): void {
        localStorage.removeItem('auth_token');
    },
};

// Configure the autogenerated client with auth and cookies
client.setConfig({
    baseUrl: API_URL,
    credentials: 'include',
    auth: () => {
        const token = localStorage.getItem('auth_token');
        return token || undefined;
    },
});

// Re-export the SDK functions and types for convenience
export * from './api-client';
