# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-01-11T13:04:35+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict


class CreateNoteRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    content: str


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: str
    code: Optional[str] = None


class Note(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    title: str
    content: str
    user_id: str
    date_created: AwareDatetime
    date_updated: AwareDatetime


class Token(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    access_token: str
    token_type: str


class UpdateNoteRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: Optional[str] = None
    content: Optional[str] = None


class User(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    email: str
    is_active: bool
    date_created: AwareDatetime
    date_updated: AwareDatetime


class UserLoginRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: str
    password: str


class UserRegisterRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: str
    password: str
